#
# This file is structured to be consumed by both humans and computers.
# It is a TOML document containing Markdown
#
[Preamble]
  title = "Maintainers"
  text = """
This file lists how the omnibus-toolchain project is maintained. When making changes
to the system, this file tells you who needs to review your patch - you need a
simple majority of maintainers for the relevant subsystems to provide a :+1: on
your pull request. Additionally, you need to not receive a veto from a
Lieutenant or the Project Lead.

Check out
[How Chef is Maintained](https://github.com/chef/chef-rfc/blob/master/rfc030-maintenance-policy.md#how-the-project-is-maintained)
for details on the process, how to become a maintainer, lieutenant, or the
project lead.
"""

[Org]
  [Org.Components]
    [Org.Components.Core]
      title = "Project Maintainer"

      lieutenant = 'scotthain'

      maintainers = [
        'schisamo',
        'yzl'
      ]

[people]
  [people.scotthain]
    name = "Scott Hain"
    github = "scotthain"

  [people.schisamo]
    name = "Seth Chisamore"
    github = "schisamo"

  [people.yzl]
    name = "Yvonne Lam"
    github = "yzl"
